canvas:
  height: 800
  width: 800
plotter:
  baudrate: 115200
  feedrate: 20000
  serial_port: ''
  x_max: 260
  x_min: 10
  y_max: 260
  y_min: 10
  z_down: 23
  z_up: 33
scribble:
  improvement_threshold: 0.0001
  max_segments: 9
  min_segments: 1
segment:
  delta_max: 1
  delta_min: -1
  length_max: 34
  length_min: 10
stroke:
  respect_white_areas: true
  thickness: 1
